@baseUrl = http://localhost:3000/api

#categories

# @name getAllCategories
GET   {{baseUrl}}/categories

###

# @name addNewCategories
POST  {{baseUrl}}/categories
Content-Type: application/json

{
  "name" : "Laptop"
}

###

# @name DeleteCategories
DELETE   {{baseUrl}}/categories/2

###

#products

# @name getAllProducts

GET {{baseUrl}}/products

###
# @name addNewProducts
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name" : "Apple"
}

###
# @name RemoveProducts

DELETE  {{baseUrl}}/products/1

